### ISSUE TITLE
More information needed to setup server on Windows

### ISSUE THREAD

**Issue by sboden** [navinesh/leave-management-system#8]
I tried installing the software.

I'm getting stuck at running the server. I ran the database.sql file in postgres. Running application.py fails because no password is supplied to connect to postgresql. I'm assuming peer authentication is assumed but no details on how to set that up in the readme section.

Error is like:
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "application.py", line 12, in <module>
    from models import Base, User, Userupdates, \
  File "C:\data\projects\reactjs\leave-management-system\server\models.py", line 20, in <module>
    Base.metadata.create_all(engine)
  File "C:\Python36\lib\site-packages\sqlalchemy\sql\schema.py", line 4005, in create_all
    tables=tables)
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1939, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "C:\Python36\lib\contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1932, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "C:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "C:\Python36\lib\site-packages\sqlalchemy\pool.py", line 400, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Python36\lib\site-packages\sqlalchemy\pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Python36\lib\site-packages\sqlalchemy\pool.py", line 529, in checkout
    rec = pool._do_get()
  File "C:\Python36\lib\site-packages\sqlalchemy\pool.py", line 1193, in _do_get
    self._dec_overflow()
  File "C:\Python36\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 249, in reraise
    raise value
  File "C:\Python36\lib\site-packages\sqlalchemy\pool.py", line 1190, in _do_get
    return self._create_connection()
  File "C:\Python36\lib\site-packages\sqlalchemy\pool.py", line 347, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Python36\lib\site-packages\sqlalchemy\pool.py", line 474, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Python36\lib\site-packages\sqlalchemy\pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "C:\Python36\lib\site-packages\psycopg2\__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) fe_sendauth: no password supplied
 (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by navinesh** [comment]
You need to setup ```lms``` user and create a password. And in your ```model.py``` and ```application.py``` create a engine using the following ```engine = create_engine('postgresql://lms:YOUR_PASSWORD@localhost:5432/leavedb')```
